default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: training_assistant_development

test:
  <<: *default
  database: training_assistant_test

production:
  <<: *default
  database: training_assistant_production
  username: training_assistant
  password: <%= ENV['SPLATOON_ENEMY_VISUALIZER_DATABASE_PASSWORD'] %>
